server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/obwiki?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/com/gec/ocean/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0  # 未删除
      logic-delete-value: 1      # 已删除
